package com.dentti.service.dentalapi.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.validation.constraints.Null;
import java.math.BigDecimal;
import java.util.Date;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@DynamoDBDocument
@DynamoDBTable(tableName = "evolucion")
public class Evolucion {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    @Null
    private String id;
    @DynamoDBAttribute
    private String usuarioId;
    @DynamoDBAttribute
    private Date fechaRegistro;
    @DynamoDBAttribute
    private String detalle;
    @DynamoDBAttribute
    private String atendidoPor;
    @DynamoDBAttribute
    private BigDecimal pagoRecibido;
}
