package com.dentti.service.dentalapi.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.validation.constraints.Null;
import java.util.List;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@DynamoDBTable(tableName = "usuario")
public class Usuario {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    @Null
    private String usuarioId;
    @DynamoDBAttribute
    private String nombre;
    @DynamoDBAttribute
    private Paciente paciente;
    @DynamoDBAttribute
    private Historia historia;
}
